uploads = []
generated = []

[[outputs]]
id = "BpGc2tk3ZlpIjgckK_Pfb"
uri = "file://dist/ACUD_Teaser_v1.tar.gz"
type = "unspecified"
title = "ACUD Teaser (updated HTML) - tar.gz archive"

[[outputs]]
id = "BYUDGUr2CrTc5yPCb-iBm"
uri = "file://dist/ACUD_Teaser.tar.gz"
type = "unspecified"
title = "ACUD Teaser Deck (standalone HTML — download, unzip, open in any browser)"
